# .github/workflows/code_checks.yaml
name: Code_Checks

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        stability: [prefer-stable]
        # Entferne PHP 8.1, da Laravel 11+ und 12.x PHP 8.2 oder höher erfordern.
        # Wenn du eine Version <= PHP 8.1 verwenden möchtest, musst du eventuell auf Laravel 10 downgraden.

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      # Git-Checkout
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # PHP-Version einrichten
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit
